import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="flex flex-col justify-between min-h-screen">
                    <Header />
                    <div className="flex-1 max-w-[1360px] mx-auto my-10 content-center">
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
